### ISSUE TITLE
Fix the purchase selling logic

### ISSUE THREAD

**Issue by Cedervall** [rintala/stock-ed#17]
- When selling 100% of one stock, the portfolio is removed, even if there is other stocks in the portfolio
- Buying over the current funds is possible, and when doing so no funds are removed
- Able to sell more stocks that exists in the portfolio, when doing so the stocks are not removed from the portfolio.

**Comment by Cedervall** [comment]
buying fixed

**Comment by Cedervall** [comment]
Think everything is fixed,

**Comment by rintala** [comment]
Resolve this in commit
